name: Nuxt Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      # ✅ 关键：强制保留 .output（绕过 gitignore）
      - name: Upload .output
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-output
          path: .output
          include-hidden-files: true
